services:
  fastapiproj_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    
  fastapiproj_app:
    image: fastapiproj_app
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - fastapiproj_database
    environment:
      DATABASE_URL: ${DATABASE_URL_TEST}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKENEM: ${ACCESS_TOKENEM}

volumes:
  pgdata:
      
